//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public int UserID { get; set; }        
        public string FullName { get; set; }
        [StringLength(6, MinimumLength=5, ErrorMessage = "5-6 char allowed!")]
        [Required(ErrorMessage="Please Provide Username", AllowEmptyStrings=false)]        
        public string Username { get; set; }
        [Required(ErrorMessage="Please provide password", AllowEmptyStrings=false)]
        [DataType( System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Password { get; set; }
    }
}
